# apiVersion 은 쿠버네티스 공식 문서에도 나와 있듯이 Pod 생성시 아래처럼 작성한다
apiVersion: v1
# 쿠버네티스에는 Pod 말고 (예: Deployment, Service, Volume 등) 다양한 종류의 리소스가 있다
kind: Pod

# metadata 는 Pod 에 대한 기본적인 정보를 작성하는것
metadata:
  # Pod 의 이름을 붙이는 것 (다른것으로 변경해도 상관없음)
  name: nginx-pod

# spec 은 Pod 에 대한 세부정보를 작성하는것
spec:
  # 하나의 Pod 내부에는 컨테이너가 들어가 있다
  # 그 컨테이너에 대한 정보를 작성하는것
  containers:
    - name: nginx-container
      # nginx 이미지를 사용
      # nginx:latest 라고 뒤에 태그명 붙여도됨 (생략하면 기본적으로 latest 붙음)
      image: nginx
      # ports 는 Pod 안에있는 컨테이너에 nginx 를 띄울때, nginx 는 몇번 port 를 사용할건지 문서화처럼 명시해주려고 작성하는것
      # 즉, 예: containerPort: 8080 으로 작성한다고 해도 실제 nginx 는 80번 포트로 띄워진다 (작동에 영향이 업다)
      ports:
        - containerPort: 80
