apiVersion: apps/v1
kind: Deployment

# Deployment 기본 정보
metadata:
  name: spring-deployment

# Deployment 세부 정보
spec:
  # 생성할 Pod 의 복제본 갯수
  replicas: 3
  # Deployment 입장에서 어떤 Pod 를 배포할지 명시적으로 나타냄
  # 예: 나는 app: backend-app 이라는 label 을 가진(matchLabel 와 일치하는) Pod 를 Deployment 를 통해 배포할거야
  selector:
    matchLabels:
      app: backend-app

  # 배포할 Pod 에 대한 정보
  template:
    metadata:
      # 레이블? 카테고리 라고 이해해면 쉽다
      # 생성할 Pod 에 카테고리를 임의로 지정해서 붙일 수 있다
      # 카테고리 종류와 세부 카테고리는 우리가 지정하기 나름
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
